apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.2
          volumeMounts:
           - name: tls
             mountPath: "/etc/ssl"
             readOnly: true
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME
              value: my-keycloak.com
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: 'true'
            - name: KC_LOG_LEVEL
              value: "INFO"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: tls
          secret:
            secretName: my-tls
            optional: false
